// https://de.wikipedia.org/wiki/Liste_von_Katzenrassen

module.exports = [
  'Abessinier',
  'American Bobtail Longhair',
  'American Bobtail Shorthair',
  'American Curl Longhair',
  'American Curl Shorthair',
  'American Shorthair',
  'American Wirehair',
  'Anatoli',
  'Angorakatze',
  'Arabische Mau',
  'Asian',
  'Australian Mist',
  'Balinese',
  'Bengal',
  'Birma',
  'Bohemian Rex',
  'Bombay',
  'Brasilianisch Kurzhaar',
  'Britisch Kurzhaar',
  'Britisch Langhaar (Highlander)',
  'Burma',
  'Burmilla',
  'California Spangled',
  'Ceylon-Katze',
  'Chantilly',
  'Chartreux',
  'Chausie',
  'Colourpoint',
  'Cornish Rex',
  'Cymric',
  'Deutsch Langhaar',
  'Devon Rex',
  'Don Sphynx',
  'Europäisch Kurzhaar',
  'Exotic Longhair',
  'Exotic Shorthair',
  'Foldex',
  'Foreign White',
  'German Rex',
  'Havana',
  'Japanese Bobtail Longhair',
  'Japanese Bobtail Shorthair',
  'Javanese',
  'Kanaani',
  'Karelian Bobtail Longhair',
  'Kartäuser-Katze',
  'Khao Manee',
  'Korat',
  'Kurilen Bobtail',
  'Kurilen Bobtail',
  'La Perm Longhair',
  'La Perm Shorthair',
  'Maine Coon',
  'Malteserkatze',
  'Mandarin',
  'Manx',
  'Mekong Bobtail',
  'Minskin',
  'Munchkin Longhair',
  'Munchkin Shorthair',
  'Nebelung',
  'Neva Masquarade',
  'Non Pointed Himalayan',
  'Norwegische Waldkatze',
  'Ocicat',
  'Ojos Azules Langhaar',
  'Ojos Azules',
  'Oregon Rex',
  'Orientalisch Kurzhaar',
  'Orientalisch Langhaar',
  'Perser',
  'Peterbald',
  'Pixiebob Longhair',
  'Pixiebob Shorthair',
  'RagaMuffin',
  'Ragdoll',
  'Russisch Blau',
  'Safari',
  'Savannah',
  'Scottish Fold Longhair',
  'Scottish Fold Shorthair',
  'Selkirk Rex Longhair',
  'Selkirk Rex Shorthair',
  'Serengeti',
  'Seychellois Longhair',
  'Seychellois Shorthair',
  'Siam',
  'Sibirische Katze',
  'Singapura',
  'Snowshoe Longhair',
  'Snowshoe',
  'Sokoke',
  'Somali',
  'Sphynx',
  'Thai',
  'Tibeter',
  'Tiffanie',
  'Tonkanese',
  'Toyger',
  'Türkisch Angora',
  'Türkisch Van',
  'Türkisch Vankedisi',
  'Ural Rex Langhaar',
  'Ural Rex',
  'Ägyptische Mau',
]

